/**
 * Session reader — reads Claude Code transcripts directly from ~/.claude/projects/.
 * Parses JSONL records, extracts user/assistant messages, filters noise.
 */

import { readdirSync, readFileSync, existsSync, statSync } from "node:fs";
import { join, basename, sep } from "node:path";
import { homedir } from "node:os";
import type {
  SessionRecord,
  SessionMessage,
  ParsedSession,
  SessionIndexEntry,
  ContentBlock,
} from "./types.js";

const CLAUDE_PROJECTS_DIR = join(homedir(), ".claude", "projects");

/** A discovered session file, with whether it's a subagent (sidechain) run. */
interface SessionFile {
  path: string;
  isSidechain: boolean;
}

/** Record types we care about for mining. */
const SIGNAL_TYPES = new Set(["user", "assistant"]);

/** Get all project slugs. */
export function listProjects(): string[] {
  if (!existsSync(CLAUDE_PROJECTS_DIR)) return [];
  return readdirSync(CLAUDE_PROJECTS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);
}

/** Load sessions-index.json for a project if it exists. */
function loadSessionIndex(
  projectSlug: string
): Map<string, SessionIndexEntry> {
  const indexPath = join(CLAUDE_PROJECTS_DIR, projectSlug, "sessions-index.json");
  const map = new Map<string, SessionIndexEntry>();
  if (!existsSync(indexPath)) return map;

  try {
    const raw = JSON.parse(readFileSync(indexPath, "utf8")) as {
      entries?: SessionIndexEntry[];
    };
    for (const entry of raw.entries ?? []) {
      map.set(entry.sessionId, entry);
    }
  } catch {
    // Corrupt index — skip
  }
  return map;
}

/** Recursively yield absolute paths of all .jsonl files under a directory. */
function* walkJsonl(dir: string): Generator<string> {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walkJsonl(full);
    } else if (entry.isFile() && entry.name.endsWith(".jsonl")) {
      yield full;
    }
  }
}

/**
 * Find all .jsonl session files in a project, recursively.
 *
 * Claude Code lays out sessions as:
 *   <project>/*.jsonl                                   — main user-agent conversations
 *   <project>/<sessionId>/subagents/*.jsonl             — sidechain subagent runs
 *
 * Anything nested inside a `subagents/` directory is flagged as sidechain.
 */
function findSessionFiles(projectSlug: string): SessionFile[] {
  const projectDir = join(CLAUDE_PROJECTS_DIR, projectSlug);
  if (!existsSync(projectDir)) return [];
  const files: SessionFile[] = [];
  const subagentsMarker = `${sep}subagents${sep}`;
  const subagentsMarkerPosix = "/subagents/";

  for (const path of walkJsonl(projectDir)) {
    const rel = path.slice(projectDir.length);
    const isSidechain =
      rel.includes(subagentsMarker) || rel.includes(subagentsMarkerPosix);
    files.push({ path, isSidechain });
  }
  return files;
}

/** Patterns for injected/wrapper blocks we don't want to treat as user signal. */
const SYSTEM_BLEED_PATTERNS = [
  /^<command-name>/,
  /^<local-command/,
  /^<user-prompt-submit-hook>/,
  /^<system-reminder>/,
  /^Caveat: The messages below were generated by/,
];

function stripSystemBleed(text: string): string {
  // If the whole block is just a system wrapper tag, drop it entirely.
  const trimmed = text.trim();
  if (SYSTEM_BLEED_PATTERNS.some((p) => p.test(trimmed))) {
    return "";
  }
  return text;
}

/** Extract text content from a message's content field. */
function extractText(content: string | ContentBlock[]): {
  text: string;
  toolUses: string[];
  isToolResult: boolean;
  isRejection: boolean;
} {
  if (typeof content === "string") {
    return {
      text: stripSystemBleed(content),
      toolUses: [],
      isToolResult: false,
      isRejection: false,
    };
  }

  const texts: string[] = [];
  const toolUses: string[] = [];
  let isToolResult = false;
  let isRejection = false;

  for (const block of content) {
    if (block.type === "text" && block.text) {
      if (block.text.includes("[Request interrupted by user")) {
        isRejection = true;
      }
      const cleaned = stripSystemBleed(block.text);
      if (cleaned) texts.push(cleaned);
    } else if (block.type === "tool_use" && block.name) {
      toolUses.push(block.name);
    } else if (block.type === "tool_result") {
      isToolResult = true;
      const inner =
        typeof block.content === "string"
          ? block.content
          : "";
      if (inner.includes("user doesn't want to proceed") || inner.includes("was rejected")) {
        isRejection = true;
        texts.push(inner);
      }
    }
  }

  return { text: texts.join("\n"), toolUses, isToolResult, isRejection };
}

/** Parse a single JSONL file into messages and a captured cwd (first seen). */
function parseSessionFile(filePath: string): {
  messages: SessionMessage[];
  cwd?: string;
} {
  let raw: string;
  try {
    raw = readFileSync(filePath, "utf8");
  } catch {
    return { messages: [] };
  }

  const messages: SessionMessage[] = [];
  let cwd: string | undefined;

  for (const line of raw.split("\n")) {
    if (!line.trim()) continue;

    let record: SessionRecord;
    try {
      record = JSON.parse(line) as SessionRecord;
    } catch {
      continue;
    }

    // Capture the first cwd we see — it's authoritative for this session.
    if (!cwd && typeof record.cwd === "string" && record.cwd.length > 0) {
      cwd = record.cwd;
    }

    if (!SIGNAL_TYPES.has(record.type)) continue;
    if (!record.message?.content) continue;

    const { text, toolUses, isToolResult, isRejection } = extractText(
      record.message.content
    );

    // Skip empty tool results that are just confirmations
    if (isToolResult && !isRejection && text.length < 20) continue;

    messages.push({
      role: record.message.role,
      text,
      timestamp: record.timestamp,
      toolUses: toolUses.length > 0 ? toolUses : undefined,
      isToolResult: isToolResult || undefined,
      isRejection: isRejection || undefined,
    });
  }

  return { messages, cwd };
}

export interface ReadOptions {
  /** Include subagent (sidechain) transcripts. Default: false — user sessions only. */
  includeSidechain?: boolean;
}

/** Read all sessions for a project. Skips subagent transcripts by default. */
export function readProject(
  projectSlug: string,
  opts: ReadOptions = {}
): ParsedSession[] {
  const sessionFiles = findSessionFiles(projectSlug);
  const filtered = opts.includeSidechain
    ? sessionFiles
    : sessionFiles.filter((f) => !f.isSidechain);
  const index = loadSessionIndex(projectSlug);
  const sessions: ParsedSession[] = [];

  for (const file of filtered) {
    const sessionId = basename(file.path, ".jsonl");
    const { messages, cwd } = parseSessionFile(file.path);

    // Skip sessions with no meaningful user messages
    if (messages.filter((m) => m.role === "user" && !m.isToolResult).length === 0) {
      continue;
    }

    sessions.push({
      sessionId,
      projectSlug,
      filePath: file.path,
      messages,
      metadata: index.get(sessionId),
      cwd,
    });
  }

  return sessions;
}

/** Read all sessions across all projects. Skips subagent transcripts by default. */
export function readAllSessions(
  filterProject?: string,
  opts: ReadOptions = {}
): ParsedSession[] {
  const slugs = filterProject
    ? [filterProject].filter((s) => existsSync(join(CLAUDE_PROJECTS_DIR, s)))
    : listProjects();

  const all: ParsedSession[] = [];
  for (const slug of slugs) {
    all.push(...readProject(slug, opts));
  }

  // Sort by first message timestamp (newest first)
  all.sort((a, b) => {
    const ta = a.messages[0]?.timestamp ?? "";
    const tb = b.messages[0]?.timestamp ?? "";
    return tb.localeCompare(ta);
  });

  return all;
}

/**
 * Reverse the Claude Code slug convention (separators → `-`) to produce a
 * best-effort label when no cwd is available. Lossy: hyphens in the original
 * path are indistinguishable from path-separator hyphens.
 */
function prettifySlug(slug: string): string {
  const homeSlug = homedir().replace(/[\\/:]/g, "-");
  if (slug === homeSlug) return "home";
  if (slug.startsWith(`${homeSlug}-dev-`)) {
    return slug.slice(homeSlug.length + 5);
  }
  if (slug.startsWith(`${homeSlug}-`)) {
    return slug.slice(homeSlug.length + 1);
  }
  return slug;
}

/**
 * Human-readable project label. Uses cwd as ground truth when available
 * (every session record has one); falls back to a best-effort slug parse.
 *
 * Examples:
 *   cwd "C:\\Users\\danit\\dev\\aristotle-cli"  → "aristotle-cli"
 *   cwd "C:\\Users\\danit\\dev\\personal-website" → "personal-website"
 *   cwd "C:\\Users\\danit"                      → "home"
 *   cwd "C:\\Users\\danit\\OneDrive\\Desktop\\X" → "desktop/X"
 *   cwd "C:\\Users\\danit\\PUNK RECORDS"        → "PUNK RECORDS"
 */
export function projectName(cwd: string | undefined, slug?: string): string {
  if (cwd && cwd.length > 0) {
    const norm = cwd.replace(/\\/g, "/").replace(/\/+$/, "");
    const home = homedir().replace(/\\/g, "/").replace(/\/+$/, "");
    if (norm === home) return "home";
    const homePrefix = `${home}/`;
    if (norm.startsWith(homePrefix)) {
      const tail = norm.slice(homePrefix.length);
      if (tail.startsWith("dev/")) return tail.slice(4);
      const onedrive = "OneDrive/Desktop/";
      if (tail.toLowerCase().startsWith(onedrive.toLowerCase())) {
        return `desktop/${tail.slice(onedrive.length)}`;
      }
      return tail;
    }
    return norm;
  }
  if (slug) return prettifySlug(slug);
  return "unknown";
}

/** Get session stats without reading full content. */
export function getSessionStats(): {
  projects: number;
  userSessions: number;
  sidechainSessions: number;
  totalSizeBytes: number;
} {
  const slugs = listProjects();
  let userSessions = 0;
  let sidechainSessions = 0;
  let totalSizeBytes = 0;

  for (const slug of slugs) {
    const files = findSessionFiles(slug);
    for (const f of files) {
      if (f.isSidechain) sidechainSessions += 1;
      else userSessions += 1;
      try {
        totalSizeBytes += statSync(f.path).size;
      } catch {
        // skip
      }
    }
  }

  return {
    projects: slugs.length,
    userSessions,
    sidechainSessions,
    totalSizeBytes,
  };
}
