/**
 * Shared normalization helpers — content-block extraction, noise filtering.
 * Used by every per-agent normalizer under ~/.skillset/sessions/ envelopes.
 */

import type { ContentBlock } from "../types.js";

const SYSTEM_BLEED_PATTERNS = [
  /^<command-name>/,
  /^<local-command/,
  /^<user-prompt-submit-hook>/,
  /^<system-reminder>/,
  /^Caveat: The messages below were generated by/,
];

export function stripSystemBleed(text: string): string {
  const trimmed = text.trim();
  if (SYSTEM_BLEED_PATTERNS.some((p) => p.test(trimmed))) return "";
  return text;
}

export interface ExtractedText {
  text: string;
  toolUses: string[];
  isToolResult: boolean;
  isRejection: boolean;
}

export function extractText(content: unknown): ExtractedText {
  if (typeof content === "string") {
    return {
      text: stripSystemBleed(content),
      toolUses: [],
      isToolResult: false,
      isRejection: false,
    };
  }
  if (!Array.isArray(content)) {
    return { text: "", toolUses: [], isToolResult: false, isRejection: false };
  }

  const texts: string[] = [];
  const toolUses: string[] = [];
  let isToolResult = false;
  let isRejection = false;

  for (const rawBlock of content) {
    if (!rawBlock || typeof rawBlock !== "object") continue;
    const block = rawBlock as ContentBlock;
    if (block.type === "text" && typeof block.text === "string") {
      if (block.text.includes("[Request interrupted by user")) {
        isRejection = true;
      }
      const cleaned = stripSystemBleed(block.text);
      if (cleaned) texts.push(cleaned);
    } else if (block.type === "tool_use" && typeof block.name === "string") {
      toolUses.push(block.name);
    } else if (block.type === "tool_result") {
      isToolResult = true;
      const inner = typeof block.content === "string" ? block.content : "";
      if (
        inner.includes("user doesn't want to proceed") ||
        inner.includes("was rejected")
      ) {
        isRejection = true;
        texts.push(inner);
      }
    }
  }

  return {
    text: texts.join("\n"),
    toolUses,
    isToolResult,
    isRejection,
  };
}
