import { readFile, readdir, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, relative } from "node:path";
import { createHash } from "node:crypto";
import matter from "gray-matter";

export type SkillTier = "high" | "medium" | "low";

export const SKILL_TIERS: readonly SkillTier[] = ["high", "medium", "low"];

export function isSkillTier(v: unknown): v is SkillTier {
  return v === "high" || v === "medium" || v === "low";
}

/**
 * Authorship of a skill. Determines whether automation may modify it.
 *  - user-created: authored by the user (directly, or adopted from a mirror the user populated).
 *    NEVER touched by automation. Can still participate in conflict reports but no state change is applied.
 *  - auto-created: generated by deep-dive / nightly / make. Eligible for edit, merge, or prune unless userEdited=true
 *    AND cleanup's tiebreaker rules say otherwise.
 */
export type SkillOrigin = "user-created" | "auto-created";

export const SKILL_ORIGINS: readonly SkillOrigin[] = ["user-created", "auto-created"];

export function isSkillOrigin(v: unknown): v is SkillOrigin {
  return v === "user-created" || v === "auto-created";
}

export interface SkillFrontmatter {
  name: string;
  description: string;
  license?: string;
  /**
   * Trust tier assigned by `sks make` triage.
   *  - high: narrow style/typography rules — auto-promote silently
   *  - medium: workflow / tool-routing / anti-patterns — auto-promote with notice
   *  - low: broad behavior changes — held as draft for review
   * Missing on legacy skills written before tiering existed.
   */
  tier?: SkillTier;
  /**
   * Authorship — determines automation's right to modify. Missing on legacy skills written
   * before origin tracking existed; treat as "user-created" for conservative safety.
   */
  origin?: SkillOrigin;
}

export interface ParsedSkill {
  frontmatter: SkillFrontmatter;
  body: string;
}

export class SkillValidationError extends Error {}

export const SKILL_NAME_PATTERN = /^(?!.*--)[a-z0-9](?:[a-z0-9-]{0,78}[a-z0-9])?$/;

export function validateSkillName(name: string): void {
  if (!SKILL_NAME_PATTERN.test(name)) {
    throw new SkillValidationError(
      "SKILL.md frontmatter `name` must be kebab-case using lowercase letters, numbers, and single hyphens"
    );
  }
}

export function parseSkillMd(source: string): ParsedSkill {
  const { data, content } = matter(source);
  if (typeof data.name !== "string" || data.name.length === 0) {
    throw new SkillValidationError("SKILL.md frontmatter is missing `name`");
  }
  validateSkillName(data.name);
  if (typeof data.description !== "string" || data.description.length === 0) {
    throw new SkillValidationError("SKILL.md frontmatter is missing `description`");
  }
  let tier: SkillTier | undefined;
  if (data.tier !== undefined && data.tier !== null) {
    if (!isSkillTier(data.tier)) {
      throw new SkillValidationError(
        `SKILL.md frontmatter \`tier\` must be one of ${SKILL_TIERS.join("|")}, got ${JSON.stringify(data.tier)}`
      );
    }
    tier = data.tier;
  }
  let origin: SkillOrigin | undefined;
  if (data.origin !== undefined && data.origin !== null) {
    if (!isSkillOrigin(data.origin)) {
      throw new SkillValidationError(
        `SKILL.md frontmatter \`origin\` must be one of ${SKILL_ORIGINS.join("|")}, got ${JSON.stringify(data.origin)}`
      );
    }
    origin = data.origin;
  }
  return {
    frontmatter: {
      name: data.name,
      description: data.description,
      license: typeof data.license === "string" ? data.license : undefined,
      tier,
      origin,
    },
    body: content,
  };
}

/**
 * Render a SKILL.md with stable frontmatter ordering (name → description → tier → origin → license).
 * Trailing newline included. Used by mirror / make / synthesize so the on-disk format is uniform.
 */
export function renderSkillMd(frontmatter: SkillFrontmatter, body: string): string {
  validateSkillName(frontmatter.name);
  const fm: string[] = [
    "---",
    `name: ${frontmatter.name}`,
    `description: ${JSON.stringify(frontmatter.description)}`,
  ];
  if (frontmatter.tier) fm.push(`tier: ${frontmatter.tier}`);
  if (frontmatter.origin) fm.push(`origin: ${frontmatter.origin}`);
  if (frontmatter.license) fm.push(`license: ${JSON.stringify(frontmatter.license)}`);
  fm.push("---");
  return fm.join("\n") + "\n\n" + body.trim() + "\n";
}

function looksLikeSkillMarkdown(text: string): boolean {
  return /^(#{1,6}\s|[-*]\s|\d+\.\s|\*\*|When\b|Always\b|Never\b|Do\b|Use\b|Prefer\b|Avoid\b|Before\b|After\b|If\b|For\b)/i.test(
    text.trimStart()
  );
}

function looksLikeWrappedSkillMarkdown(text: string): boolean {
  const clean = text.trimStart();
  return (
    /^#{1,6}\s.+\n\s*\n/.test(clean) ||
    /^([-*]\s|\d+\.\s|\*\*|When\b|Always\b|Never\b|Do\b|Use\b|Prefer\b|Avoid\b|Before\b|After\b|If\b|For\b)/i.test(
      clean
    )
  );
}

/**
 * Clean common LLM markdown wrappers from generated skill bodies without
 * touching ordinary body text or real code examples.
 */
export function normalizeGeneratedSkillBody(body: string): string {
  const clean = body.trim();

  const fencedWrapper = clean.match(/^```(?:markdown|md)\s*\n([\s\S]*?)\n```\s*$/i);
  if (fencedWrapper) {
    return fencedWrapper[1]!.trim();
  }

  const bareFencedWrapper = clean.match(/^```\s*\n([\s\S]*?)\n```\s*$/);
  if (bareFencedWrapper) {
    const inner = bareFencedWrapper[1]!.trim();
    return looksLikeWrappedSkillMarkdown(inner) ? inner : clean;
  }

  const markdownOpeningFence = clean.match(/^```(?:markdown|md)\s*\n?/i);
  if (markdownOpeningFence) {
    const rest = clean.slice(markdownOpeningFence[0].length).trimStart();
    if (looksLikeSkillMarkdown(rest)) return rest.trim();
  }

  const bareOpeningFence = clean.match(/^```\s*\n?/);
  if (bareOpeningFence) {
    const rest = clean.slice(bareOpeningFence[0].length).trimStart();
    if (looksLikeSkillMarkdown(rest)) return rest.trim();
  }

  return clean;
}

export async function readSkillMd(skillDir: string): Promise<ParsedSkill> {
  const path = join(skillDir, "SKILL.md");
  if (!existsSync(path)) {
    throw new SkillValidationError(`No SKILL.md at ${path}`);
  }
  return parseSkillMd(await readFile(path, "utf8"));
}

export async function listSkillDirs(skillsRoot: string): Promise<string[]> {
  if (!existsSync(skillsRoot)) return [];
  const entries = await readdir(skillsRoot, { withFileTypes: true });
  const dirs: string[] = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (existsSync(join(skillsRoot, entry.name, "SKILL.md"))) {
      dirs.push(join(skillsRoot, entry.name));
    }
  }
  return dirs.sort();
}

export async function hashSkillDir(skillDir: string): Promise<string> {
  const files = await collectFiles(skillDir);
  const hash = createHash("sha256");
  for (const rel of files.sort()) {
    const abs = join(skillDir, rel);
    const buf = await readFile(abs);
    hash.update(rel);
    hash.update("\0");
    hash.update(buf);
    hash.update("\0");
  }
  return hash.digest("hex");
}

async function collectFiles(root: string, base = root): Promise<string[]> {
  const out: string[] = [];
  const entries = await readdir(root, { withFileTypes: true });
  for (const entry of entries) {
    const abs = join(root, entry.name);
    if (entry.isDirectory()) {
      out.push(...(await collectFiles(abs, base)));
    } else if (entry.isFile()) {
      out.push(relative(base, abs).split("\\").join("/"));
    }
  }
  return out;
}

export async function skillDirExists(skillsRoot: string, name: string): Promise<boolean> {
  const dir = join(skillsRoot, name);
  if (!existsSync(dir)) return false;
  const s = await stat(dir);
  return s.isDirectory() && existsSync(join(dir, "SKILL.md"));
}
